{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for Choc.
--   Generated by the BNF converter.

module Choc.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Choc.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Choc.Abs.Ident where
  prt _ (Choc.Abs.Ident i) = doc $ showString i

instance Print Choc.Abs.Program where
  prt i = \case
    Choc.Abs.Program topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print Choc.Abs.TopDef where
  prt i = \case
    Choc.Abs.FnDef type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [Choc.Abs.TopDef] where
  prt = prtList

instance Print Choc.Abs.Arg where
  prt i = \case
    Choc.Abs.ArgNoRef type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])
    Choc.Abs.ArgRef type_ id_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "&"), prt 0 id_])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Choc.Abs.Arg] where
  prt = prtList

instance Print Choc.Abs.Block where
  prt i = \case
    Choc.Abs.Block stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [Choc.Abs.Stmt] where
  prt = prtList

instance Print Choc.Abs.Stmt where
  prt i = \case
    Choc.Abs.Empty -> prPrec i 0 (concatD [doc (showString ";")])
    Choc.Abs.BStmt block -> prPrec i 0 (concatD [prt 0 block])
    Choc.Abs.Decl type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    Choc.Abs.Ass id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    Choc.Abs.Incr id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "++"), doc (showString ";")])
    Choc.Abs.Decr id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "--"), doc (showString ";")])
    Choc.Abs.Ret expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    Choc.Abs.VRet -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    Choc.Abs.Cond expr block -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    Choc.Abs.CondElse expr block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block1, doc (showString "else"), prt 0 block2])
    Choc.Abs.While expr block -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    Choc.Abs.SExp expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
    Choc.Abs.Break -> prPrec i 0 (concatD [doc (showString "break")])
    Choc.Abs.Continue -> prPrec i 0 (concatD [doc (showString "continue")])
    Choc.Abs.FnNestDef topdef -> prPrec i 0 (concatD [prt 0 topdef, doc (showString ";")])
    Choc.Abs.SPrint expr -> prPrec i 0 (concatD [doc (showString "print"), doc (showString "("), prt 0 expr, doc (showString ")"), doc (showString ";")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Choc.Abs.Item where
  prt i = \case
    Choc.Abs.NoInit id_ -> prPrec i 0 (concatD [prt 0 id_])
    Choc.Abs.Init id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Choc.Abs.Item] where
  prt = prtList

instance Print Choc.Abs.Type where
  prt i = \case
    Choc.Abs.Int -> prPrec i 0 (concatD [doc (showString "int")])
    Choc.Abs.Str -> prPrec i 0 (concatD [doc (showString "string")])
    Choc.Abs.Bool -> prPrec i 0 (concatD [doc (showString "boolean")])
    Choc.Abs.Void -> prPrec i 0 (concatD [doc (showString "void")])
    Choc.Abs.Function type_ types -> prPrec i 0 (concatD [doc (showString "function"), doc (showString "<"), prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")"), doc (showString ">")])
    Choc.Abs.Fun type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Choc.Abs.Type] where
  prt = prtList

instance Print Choc.Abs.Expr where
  prt i = \case
    Choc.Abs.EVar id_ -> prPrec i 6 (concatD [prt 0 id_])
    Choc.Abs.ELitInt n -> prPrec i 6 (concatD [prt 0 n])
    Choc.Abs.ELitTrue -> prPrec i 6 (concatD [doc (showString "true")])
    Choc.Abs.ELitFalse -> prPrec i 6 (concatD [doc (showString "false")])
    Choc.Abs.EApp id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    Choc.Abs.EString str -> prPrec i 6 (concatD [prt 0 str])
    Choc.Abs.Neg expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    Choc.Abs.Not expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    Choc.Abs.EMul expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    Choc.Abs.EAdd expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    Choc.Abs.ERel expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    Choc.Abs.EAnd expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    Choc.Abs.EOr expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
    Choc.Abs.ELambda lambda -> prPrec i 0 (concatD [prt 0 lambda])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Choc.Abs.Expr] where
  prt = prtList

instance Print Choc.Abs.Lambda where
  prt i = \case
    Choc.Abs.LambdaDef type_ args block -> prPrec i 0 (concatD [doc (showString "lambda"), doc (showString "<"), prt 0 type_, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString ">"), prt 0 block])

instance Print Choc.Abs.AddOp where
  prt i = \case
    Choc.Abs.Plus -> prPrec i 0 (concatD [doc (showString "+")])
    Choc.Abs.Minus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print Choc.Abs.MulOp where
  prt i = \case
    Choc.Abs.Times -> prPrec i 0 (concatD [doc (showString "*")])
    Choc.Abs.Div -> prPrec i 0 (concatD [doc (showString "/")])
    Choc.Abs.Mod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print Choc.Abs.RelOp where
  prt i = \case
    Choc.Abs.LTH -> prPrec i 0 (concatD [doc (showString "<")])
    Choc.Abs.LE -> prPrec i 0 (concatD [doc (showString "<=")])
    Choc.Abs.GTH -> prPrec i 0 (concatD [doc (showString ">")])
    Choc.Abs.GE -> prPrec i 0 (concatD [doc (showString ">=")])
    Choc.Abs.EQU -> prPrec i 0 (concatD [doc (showString "==")])
    Choc.Abs.NE -> prPrec i 0 (concatD [doc (showString "!=")])

