-- Haskell module generated by the BNF converter

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Choc.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Choc.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Choc.Abs.Ident -> Result
transIdent x = case x of
  Choc.Abs.Ident string -> failure x

transProgram :: Show a => Choc.Abs.Program' a -> Result
transProgram x = case x of
  Choc.Abs.Program _ topdefs -> failure x

transTopDef :: Show a => Choc.Abs.TopDef' a -> Result
transTopDef x = case x of
  Choc.Abs.FnDef _ type_ ident args block -> failure x

transArg :: Show a => Choc.Abs.Arg' a -> Result
transArg x = case x of
  Choc.Abs.ArgNoRef _ type_ ident -> failure x
  Choc.Abs.ArgRef _ type_ ident -> failure x

transBlock :: Show a => Choc.Abs.Block' a -> Result
transBlock x = case x of
  Choc.Abs.Block _ stmts -> failure x

transStmt :: Show a => Choc.Abs.Stmt' a -> Result
transStmt x = case x of
  Choc.Abs.Empty _ -> failure x
  Choc.Abs.BStmt _ block -> failure x
  Choc.Abs.Decl _ type_ items -> failure x
  Choc.Abs.Ass _ ident expr -> failure x
  Choc.Abs.Incr _ ident -> failure x
  Choc.Abs.Decr _ ident -> failure x
  Choc.Abs.Ret _ expr -> failure x
  Choc.Abs.VRet _ -> failure x
  Choc.Abs.Cond _ expr block -> failure x
  Choc.Abs.CondElse _ expr block1 block2 -> failure x
  Choc.Abs.While _ expr block -> failure x
  Choc.Abs.SExp _ expr -> failure x
  Choc.Abs.Break _ -> failure x
  Choc.Abs.Continue _ -> failure x
  Choc.Abs.SPrint _ expr -> failure x

transItem :: Show a => Choc.Abs.Item' a -> Result
transItem x = case x of
  Choc.Abs.NoInit _ ident -> failure x
  Choc.Abs.Init _ ident expr -> failure x

transType :: Show a => Choc.Abs.Type' a -> Result
transType x = case x of
  Choc.Abs.Int _ -> failure x
  Choc.Abs.Str _ -> failure x
  Choc.Abs.Bool _ -> failure x
  Choc.Abs.Void _ -> failure x
  Choc.Abs.Fun _ type_ types -> failure x

transExpr :: Show a => Choc.Abs.Expr' a -> Result
transExpr x = case x of
  Choc.Abs.EVar _ ident -> failure x
  Choc.Abs.ELitInt _ integer -> failure x
  Choc.Abs.ELitTrue _ -> failure x
  Choc.Abs.ELitFalse _ -> failure x
  Choc.Abs.EApp _ ident exprs -> failure x
  Choc.Abs.EString _ string -> failure x
  Choc.Abs.Neg _ expr -> failure x
  Choc.Abs.Not _ expr -> failure x
  Choc.Abs.EMul _ expr1 mulop expr2 -> failure x
  Choc.Abs.EAdd _ expr1 addop expr2 -> failure x
  Choc.Abs.ERel _ expr1 relop expr2 -> failure x
  Choc.Abs.EAnd _ expr1 expr2 -> failure x
  Choc.Abs.EOr _ expr1 expr2 -> failure x

transAddOp :: Show a => Choc.Abs.AddOp' a -> Result
transAddOp x = case x of
  Choc.Abs.Plus _ -> failure x
  Choc.Abs.Minus _ -> failure x

transMulOp :: Show a => Choc.Abs.MulOp' a -> Result
transMulOp x = case x of
  Choc.Abs.Times _ -> failure x
  Choc.Abs.Div _ -> failure x
  Choc.Abs.Mod _ -> failure x

transRelOp :: Show a => Choc.Abs.RelOp' a -> Result
transRelOp x = case x of
  Choc.Abs.LTH _ -> failure x
  Choc.Abs.LE _ -> failure x
  Choc.Abs.GTH _ -> failure x
  Choc.Abs.GE _ -> failure x
  Choc.Abs.EQU _ -> failure x
  Choc.Abs.NE _ -> failure x
