{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintChococino.
--   Generated by the BNF converter.

module PrintChococino where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsChococino

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsChococino.Ident where
  prt _ (AbsChococino.Ident i) = doc $ showString i

instance Print (AbsChococino.Program' a) where
  prt i = \case
    AbsChococino.Program _ topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print (AbsChococino.TopDef' a) where
  prt i = \case
    AbsChococino.FnDef _ type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsChococino.TopDef' a] where
  prt = prtList

instance Print (AbsChococino.Arg' a) where
  prt i = \case
    AbsChococino.ArgNoRef _ type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])
    AbsChococino.ArgRef _ type_ id_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "&"), prt 0 id_])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsChococino.Arg' a] where
  prt = prtList

instance Print (AbsChococino.Block' a) where
  prt i = \case
    AbsChococino.Block _ stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [AbsChococino.Stmt' a] where
  prt = prtList

instance Print (AbsChococino.Stmt' a) where
  prt i = \case
    AbsChococino.Empty _ -> prPrec i 0 (concatD [doc (showString ";")])
    AbsChococino.BStmt _ block -> prPrec i 0 (concatD [prt 0 block])
    AbsChococino.Decl _ type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    AbsChococino.Ass _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsChococino.Incr _ id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "++"), doc (showString ";")])
    AbsChococino.Decr _ id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "--"), doc (showString ";")])
    AbsChococino.Ret _ expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsChococino.VRet _ -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsChococino.Cond _ expr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsChococino.CondElse _ expr stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2])
    AbsChococino.While _ expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsChococino.SExp _ expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (AbsChococino.Item' a) where
  prt i = \case
    AbsChococino.NoInit _ id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsChococino.Init _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsChococino.Item' a] where
  prt = prtList

instance Print (AbsChococino.Type' a) where
  prt i = \case
    AbsChococino.Int _ -> prPrec i 0 (concatD [doc (showString "int")])
    AbsChococino.Str _ -> prPrec i 0 (concatD [doc (showString "string")])
    AbsChococino.Bool _ -> prPrec i 0 (concatD [doc (showString "boolean")])
    AbsChococino.Void _ -> prPrec i 0 (concatD [doc (showString "void")])
    AbsChococino.Fun _ type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsChococino.Type' a] where
  prt = prtList

instance Print (AbsChococino.Expr' a) where
  prt i = \case
    AbsChococino.EVar _ id_ -> prPrec i 6 (concatD [prt 0 id_])
    AbsChococino.ELitInt _ n -> prPrec i 6 (concatD [prt 0 n])
    AbsChococino.ELitTrue _ -> prPrec i 6 (concatD [doc (showString "true")])
    AbsChococino.ELitFalse _ -> prPrec i 6 (concatD [doc (showString "false")])
    AbsChococino.EApp _ id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsChococino.EString _ str -> prPrec i 6 (concatD [prt 0 str])
    AbsChococino.Neg _ expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsChococino.Not _ expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    AbsChococino.EMul _ expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsChococino.EAdd _ expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsChococino.ERel _ expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AbsChococino.EAnd _ expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    AbsChococino.EOr _ expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsChococino.Expr' a] where
  prt = prtList

instance Print (AbsChococino.AddOp' a) where
  prt i = \case
    AbsChococino.Plus _ -> prPrec i 0 (concatD [doc (showString "+")])
    AbsChococino.Minus _ -> prPrec i 0 (concatD [doc (showString "-")])

instance Print (AbsChococino.MulOp' a) where
  prt i = \case
    AbsChococino.Times _ -> prPrec i 0 (concatD [doc (showString "*")])
    AbsChococino.Div _ -> prPrec i 0 (concatD [doc (showString "/")])
    AbsChococino.Mod _ -> prPrec i 0 (concatD [doc (showString "%")])

instance Print (AbsChococino.RelOp' a) where
  prt i = \case
    AbsChococino.LTH _ -> prPrec i 0 (concatD [doc (showString "<")])
    AbsChococino.LE _ -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsChococino.GTH _ -> prPrec i 0 (concatD [doc (showString ">")])
    AbsChococino.GE _ -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsChococino.EQU _ -> prPrec i 0 (concatD [doc (showString "==")])
    AbsChococino.NE _ -> prPrec i 0 (concatD [doc (showString "!=")])

